# JDBC connection
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/homework_2
hibernate.connection.username=postgres
hibernate.connection.password=1234

# SQL logs
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.highlight_sql=false

# Schema generation
hibernate.hbm2ddl.auto=create